site_name: TIPNNV Resources
site_url: "https://resources.tipnnv.org"
site_description: The Trauma Intervention Program of Northern Nevada provides resources to those experiencing a tragedy. Learn more about our resources here.
theme:
  name: material
  features:
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
  logo: assets/TIPNNV-Main-Circle-Logo-with-Thin-Outline.svg
  language: en
  palette:
      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: indigo
      accent: red
      
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: indigo
      accent: red
  favicon: images/TIP-Letters.svg

nav:
  - Home: index.md 
  - Coping After a Tragedy: coping-after-a-tragedy.md
  - Emotional First Aid: emotional-first-aid.md
  - Coroner's Office: coroner's-office.md
  - Estates/Paperwork: handling-estates.md
  - Fire: fire.md
  - Media: media.md
  - Recursos En Español: recursos-en-espanol.md
  - Support Services Directory: support-services-directory.md

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - search:
  - privacy:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/privacy
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tipnnv
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TIPNNV/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@TIPNNV
  homepage: https://tipnnv.org
  analytics:
    provider: google
    property: G-8VT097M09V
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback!

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our resources and whether users
      find what they're searching for. With your consent, you're helping us to
      make our resources better.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - admonition:
  - pymdownx.arithmatex:
      generic: 
  - footnotes:
  - pymdownx.superfences:
  - attr_list:
  - md_in_html:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 2
  - tables
  - def_list
  - smarty

validation:
  omitted_files: warn
  absolute_links: relative_to_docs  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6

copyright: |
  &copy; 2024 <a href="https://tipnnv.org" target="_blank" rel="noopener">Trauma Intervention Program of Northern Nevada</a> <br> 
  <a href="#__consent">Change cookie settings</a>

