site_name: Trauma Intervention Program of Northern Nevada - Resources
site_url: ""
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo: assets/TIPNN-Heart-with-Pulse-Left-Long-Logo.svg
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: red
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: red
  favicon: images/TIP-Letters.svg

plugins:
  - privacy:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/privacy
      log: true
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external
      links: true
      links_noopener: true
  - search:
      

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tipnnv
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TIPNNV/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@TIPNNV

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our resources and whether users
      find what they're searching for. With your consent, you're helping us to
      make our resources better.


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: 
  - footnotes
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://tipnnv.org" target="_blank" rel="noopener">Trauma Intervention Program of Northern Nevada</a> - 
  <a href="#__consent">Change cookie settings</a>

